on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login --username $DOCKER_USERNAME --password-stdin
